### PR TITLE
Improve Travis configuration

### PR DESCRIPTION
**Pull request by WouterJ**

### CODE REVIEW

**Comment by gnugat** [comment]
Is there a way to re-run the test? Currently it says it is caused by some permission issue which don't appear on other suites...

**Comment by WouterJ** [comment]
Hit the refresh icon on the top right of the job or build you want to re-run. Only people with push access can do that

**Comment by gnugat** [comment]
Cheers. I've re-run and still get this permission issue on copies of fixtures. Those files are created by the user who runs the test suite (we create them using Symfony's `Filesystem#copy`). Looks like we've hitted some kind of bug in Symfony 2.4.1?

**Comment by WouterJ** [comment]
Hmm, I can't find it while looking at the git history. Let's try using the latest 2.4.x version of Symfony to see if it was indeed a bug in earlier 2.4.x version (and then, let's lower it until we find the correct version).

**Comment by WouterJ** [comment]
Did some try and error and it turns out 2.4.3 has a bugfix for the bug we're hitting. Travis should now pass and make this PR ready to merge :)

**Comment by WouterJ** [comment]
And now made a final commit in this PR:

* Cache `$HOME/.composer/cache` instead of `vendor`, as Composer has a cache bug for `vendor` and branch aliases.
* Update config to have a `$COMPOSER_FLAGS` variable, so we can just use one call
* Removed `--prefer-source`, to make composer install packages from `$HOME/.composer/cache`.

**Comment by gnugat** [comment]
Thank you so much for this, you've done a brilliant job!

**Pull request merged**
